language: android

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

android:
  components:
    # The BuildTools version used by your project
    - build-tools-25.0.0
    # The SDK version used to compile your project
    - android-25

script:
   - ./gradlew clean testDebugUnitTest